/*TRAVAIL DU BOIS*/

				ACHAT DE COUPE DE BOIS, TRANSFORMATION ET VENTE DE BOIS DE CHAUFFAGE
				ACHAT REVENTE DE BOIS SUR PIED
				CHANTOURNAGE SUR BOIS
				COMMERCE DE DETAIL DE BOIS DE CHAUFFAGE ET PRODUITS DERIVES
				CONSTRUCTEUR BOIS (CHALETS, CABANES DANS LES ARBRES, ABRIS DE JARDIN, ETC)
				EBENISTERIE
				EXPLOITANT FORESTIER NEGOCIANT (VENTE POUR SON PROPRE COMPTE)
				FABRICATION D\'ACCESSOIRES DE MUSIQUE EN BOIS (METRONOME, ETC)
				FABRICATION DE BACS EN BOIS POUR POTAGER
				FABRICATION DE CAISSES EN BOIS
				FABRICATION DE CHARPENTES
				FABRICATION DE CONTREPLAQUES, BOIS PLAQUES, PANNEAUX
				FABRICATION DE JEUX EN BOIS (PUZZLE, JEUX DE SOCIETE, ETC )
				FABRICATION DE JOUETS EN BOIS
				FABRICATION D\'EMBALLAGES ET TOUS CONDITIONNEMENTS EN BOIS
				FABRICATION DE MENUISERIES (PLINTHES, PORTES, FENETRES, ETC )
				FABRICATION DE MOBILIER EN BOIS
				FABRICATION DE PALETTES EN BOIS
				FABRICATION DE PARQUETS ASSEMBLES (LAMES EN PANNEAUX)
				FABRICATION DE PIQUETS EN BOIS
				FABRICATION DE POULAILLERS EN BOIS
				FABRICATION DE SABOTS EN BOIS
				FABRICATION D\'OBJETS DECORATIFS EN BOIS
				FABRICATION D\'OBJETS DIVERS EN BOIS
				FABRICATION D\'OBJETS UTILITAIRES EN BOIS (USTENSILES DE CUISINE, ETC)
				FABRICATION D\'OUVRAGES DE TONNELLERIE EN BOIS ( FUTS, ETC)
				FABRICATION D\'OUVRAGES EN BOIS MARQUETE
				FINITIONS DE MEUBLES EN BOIS (DORURE, PEINTURE, ETC)
				IMPREGNATION DU BOIS
				LUTHERIE
				MENUISERIE BOIS				
				MONTAGE DE CONSTRUCTIONS BOIS (MAISONS EN KIT, ETC)
				MONTAGE ET POSE DE MEUBLES EN BOIS				
				PARQUETTISTE
				RAMASSAGE, TRI ET REPARATION DE PALETTES EN BOIS
				RELOOKING DE MEUBLES EN BOIS
				RENOVATION DE PARQUETS (PONCAGE, VITRIFICATION, ETC )
				REPARATION D\'OUVRAGES DE TONNELLERIE EN BOIS ( FUTS, ETC)
				RESTAURATION DE MEUBLES EN BOIS (PATINE, ETC)
				TOURNAGE SUR BOIS
				TRAITEMENTS CONSERVATEURS DU BOIS (CONTRE LES INSECTES, LES CHAMPIGNONS, ETC)
				TRANSFORMATION DU BOIS (SCIAGE, RABOTAGE, ETC)
				VERNISSAGE D\'OUVRAGES EN BOIS
				
				


/*TRAVAIL DU METAL*/


				AFFUTAGE DE COUTEAUX
				AFFUTAGE DE LAMES ET SCIES POUR MACHINES
				APPLICATION DE MATERIAUX COMPOSITES SUR METAUX
				CHAUDRONNERIE
				DECOLLETAGE
				DECOUPAGE A FACON DE METAUX
				DINANDERIE
				DORURE SUR METAL
				FABRICATION D\'ACCESSOIRES DE TUYAUTERIE EN ACIER
				FABRICATION D\'ARMATURES POUR BETON ARME
				FABRICATION D\'ARTICLES DIVERS EN METAUX COMMUNS
				FABRICATION DE COUTELLERIE
				FABRICATION DE COUTELLERIE D\'ART
				FABRICATION DE GRILLES METALLIQUES ANTI INTRUSION
				FABRICATION DE MENUISERIES METALLIQUES
				FABRICATION DE PIECES EN FONTE DE METAUX LEGERS
				FABRICATION DE SERRURES
				FABRICATION DE STRUCTURES METALLIQUES
				FABRICATION DE TAILLANDERIE
				FABRICATION DE TOUS TYPES DE TUYAUTERIES INDUSTRIELLES EN ACIER
				FABRICATION D\'OBJETS DE DECORATION EN FER FORGE
				FABRICATION D\'OBJETS EN BRONZE
				FABRICATION D\'OBJETS EN GRILLAGE
				FABRICATION D\'OBJETS EN METAL
				FERRONNERIE D\'ART
				FONDERIE D\'ART
				GRAVURE SUR METAUX
				INSTALLATION DE STRUCTURES METALLIQUES CHAUDRONNEES
				PERSONNALISATION DE SUPPORTS METALLIQUES (MARQUAGE, PEINTURE, ETC)
				PLIAGE A FACON DE METAUX
				POSE DE MENUISERIE METALLIQUE
				POSE DE METALLERIE SERRURERIE
				PROFILAGE DE METAUX
				REPARATION D\'ARTICLES DE COUTELLERIE
				REPARATION D\'OUTILS  EN METAL
				REPARATION D\'OUVRAGES EN METAUX
				TRAITEMENT DE SURFACES METALLIQUES
				USINAGE DE PIECES EN METAL
				
/*TRAVAIL DU CUIR*/

				APPRET ET TANNAGE DES CUIRS</option>
				
				<option style="width:300px;" value="252137" title="BOURELLERIE">
				BOURELLERIE</option>
				
				<option style="width:300px;" value="252138" title="COMMERCE DE DETAIL D'ACCESSOIRES DE VOYAGE">
				COMMERCE DE DETAIL D'ACCESSOIRES DE VOYAGE</option>
				
				<option style="width:300px;" value="252139" title="COMMERCE DE DETAIL DE MAROQUINERIE">
				COMMERCE DE DETAIL DE MAROQUINERIE</option>
				
				<option style="width:300px;" value="252140" title="CONCEPTION ET FABRICATION DE SACS DE TRANSPORT POUR ANIMAUX DE COMPAGNIE">
				CONCEPTION ET FABRICATION DE SACS DE TRANSPORT POUR ANIMAUX DE COMPAGNIE</option>
				
				<option style="width:300px;" value="252141" title="FABRICATION D'ACCESSOIRES EN CUIR">
				FABRICATION D'ACCESSOIRES EN CUIR</option>
				
				<option style="width:300px;" value="252142" title="FABRICATION D'ARTICLES DE VOYAGE, D'ARTICLES DE MAROQUINERIE ET D'ARTICLES SIMILAIRES (SACS DE SPORTS, ETC.)">
				FABRICATION D'ARTICLES DE VOYAGE, D'ARTICLES DE MAROQUINERIE ET D'ARTICLES SIMILAIRES (SACS DE SPORTS, ETC.)</option>
				
				<option style="width:300px;" value="252143" title="FABRICATION D'ARTICLES DIVERS EN CUIR (BACHES, HOUSSES DE PROTECTION, COURROIES, JOINTS,)">
				FABRICATION D'ARTICLES DIVERS EN CUIR (BACHES, HOUSSES DE PROTECTION, COURROIES, JOINTS,)</option>
				
				<option style="width:300px;" value="252144" title="FABRICATION DE BOTTES EN CUIR">
				FABRICATION DE BOTTES EN CUIR</option>
				
				<option style="width:300px;" value="252145" title="FABRICATION DE BRACELETS DE MONTRE EN CUIR">
				FABRICATION DE BRACELETS DE MONTRE EN CUIR</option>
				
				<option style="width:300px;" value="252146" title="FABRICATION DE GANTS EN CUIR">
				FABRICATION DE GANTS EN CUIR</option>
				
				<option style="width:300px;" value="252147" title="FABRICATION DE GUETRES EN CUIR">
				FABRICATION DE GUETRES EN CUIR</option>
				
				<option style="width:300px;" value="252148" title="FABRICATION DE LACETS EN CUIR">
				FABRICATION DE LACETS EN CUIR</option>
				
				<option style="width:300px;" value="252149" title="FABRICATION DE VETEMENTS EN CUIR">
				FABRICATION DE VETEMENTS EN CUIR</option>
				
				<option style="width:300px;" value="252150" title="GAINERIE">
				GAINERIE</option>
				
				<option style="width:300px;" value="252151" title="HARNACHEUR (FABRICATION DE FOUETS, CRAVACHES, HARNAIS, ETC)">
				HARNACHEUR (FABRICATION DE FOUETS, CRAVACHES, HARNAIS, ETC)</option>
				
				<option style="width:300px;" value="252152" title="RECOLORATION DU CUIR">
				RECOLORATION DU CUIR</option>
				
				<option style="width:300px;" value="252153" title="REPARATION DE CHAUSSURES ET ARTICLES EN CUIR">
				REPARATION DE CHAUSSURES ET ARTICLES EN CUIR</option>
				
				<option style="width:300px;" value="252154" title="RETAILLE DU CUIR">
				RETAILLE DU CUIR</option>
				
				<option style="width:300px;" value="252155" title="SELLERIE">
				SELLERIE</option>
				
				<option style="width:300px;" value="252156" title="SELLERIE (AUTOMOBILE, MOTO, MARINE, ETC)">
				SELLERIE (AUTOMOBILE, MOTO, MARINE, ETC)</option>
				
				<option style="width:300px;" value="252157" title="SELLERIE GENERALE">
				SELLERIE GENERALE</option>
				
				<option style="width:300px;" value="252158" title="SELLIER BOURRELIER">
				SELLIER BOURRELIER</option>
				
				<option style="width:300px;" value="252159" title="SELLIER GARNISSEUR">
				SELLIER GARNISSEUR</option>
				
				<option style="width:300px;" value="252160" title="SELLIER HARNACHEUR">
				SELLIER HARNACHEUR</option>
				
/*TEXTILE*/


				BRODERIE A FACON SUR VETEMENTS</option>
				
				<option style="width:300px;" value="252162" title="BRODERIE SUR TEXTILE">
				BRODERIE SUR TEXTILE</option>
				
				<option style="width:300px;" value="252163" title="CONFECTION TEXTILE POUR L'AMENAGEMENT EXTERIEUR">
				CONFECTION TEXTILE POUR L'AMENAGEMENT EXTERIEUR</option>
				
				<option style="width:300px;" value="252164" title="CUSTOMISATION DE VETEMENTS ET ACCESSOIRES">
				CUSTOMISATION DE VETEMENTS ET ACCESSOIRES</option>
				
				<option style="width:300px;" value="252165" title="ENNOBLISSEMENT TEXTILE">
				ENNOBLISSEMENT TEXTILE</option>
				
				<option style="width:300px;" value="252166" title="FABRICATION D'ACCESSOIRES DE COIFFURE EN TISSU">
				FABRICATION D'ACCESSOIRES DE COIFFURE EN TISSU</option>
				
				<option style="width:300px;" value="252167" title="FABRICATION D'ACCESSOIRES DE MODE EN TISSU (SACS, PORTE-MONNAIE, BIJOUX, BROCHES, PORTE-CARTES,...)">
				FABRICATION D'ACCESSOIRES DE MODE EN TISSU (SACS, PORTE-MONNAIE, BIJOUX, BROCHES, PORTE-CARTES,...)</option>
				
				<option style="width:300px;" value="252168" title="FABRICATION D'ARTICLES DE CAMPEMENT EN TEXTILE">
				FABRICATION D'ARTICLES DE CAMPEMENT EN TEXTILE</option>
				
				<option style="width:300px;" value="252169" title="FABRICATION D'ARTICLES DE CORDERIE">
				FABRICATION D'ARTICLES DE CORDERIE</option>
				
				<option style="width:300px;" value="252170" title="FABRICATION D'ARTICLES DE RUBANERIE">
				FABRICATION D'ARTICLES DE RUBANERIE</option>
				
				<option style="width:300px;" value="252171" title="FABRICATION D'ARTICLES EN TOUTES MATIERES TEXTILES">
				FABRICATION D'ARTICLES EN TOUTES MATIERES TEXTILES</option>
				
				<option style="width:300px;" value="252172" title="FABRICATION D'ARTICLES TEXTILES D'AMEUBLEMENT">
				FABRICATION D'ARTICLES TEXTILES D'AMEUBLEMENT</option>
				
				<option style="width:300px;" value="252173" title="FABRICATION D'ARTICLES TEXTILES TECHNIQUES">
				FABRICATION D'ARTICLES TEXTILES TECHNIQUES</option>
				
				<option style="width:300px;" value="252174" title="FABRICATION DE BACHES">
				FABRICATION DE BACHES</option>
				
				<option style="width:300px;" value="252175" title="FABRICATION DE DENTELLE">
				FABRICATION DE DENTELLE</option>
				
				<option style="width:300px;" value="252176" title="FABRICATION DE DOUDOUS EN TISSU">
				FABRICATION DE DOUDOUS EN TISSU</option>
				
				<option style="width:300px;" value="252177" title="FABRICATION DE FEUTRES">
				FABRICATION DE FEUTRES</option>
				
				<option style="width:300px;" value="252178" title="FABRICATION DE LINGE DE MAISON">
				FABRICATION DE LINGE DE MAISON</option>
				
				<option style="width:300px;" value="252179" title="FABRICATION DE PIECES DE BRODERIE">
				FABRICATION DE PIECES DE BRODERIE</option>
				
				<option style="width:300px;" value="252180" title="FABRICATION DE PIECES TEXTILES MATELASSEES, REMBOURREES OU CAPITONNEES">
				FABRICATION DE PIECES TEXTILES MATELASSEES, REMBOURREES OU CAPITONNEES</option>
				
				<option style="width:300px;" value="252181" title="FABRICATION DE TAPIS">
				FABRICATION DE TAPIS</option>
				
				<option style="width:300px;" value="252182" title="FABRICATION DE TAPISSERIE A LA MAIN">
				FABRICATION DE TAPISSERIE A LA MAIN</option>
				
				<option style="width:300px;" value="252187" title="FABRICATION D'ETIQUETTES ET D'ECUSSONS EN MATIERE TEXTILE">
				FABRICATION D'ETIQUETTES ET D'ECUSSONS EN MATIERE TEXTILE</option>
				
				<option style="width:300px;" value="252184" title="FABRICATION DE TISSUS TRAITES OU ENDUITS">
				FABRICATION DE TISSUS TRAITES OU ENDUITS</option>
				
				<option style="width:300px;" value="252183" title="FABRICATION DE TISSUS (TRICOTES, CROCHETES, ETC)">
				FABRICATION DE TISSUS (TRICOTES, CROCHETES, ETC)</option>
				
				<option style="width:300px;" value="252188" title="FABRICATION D'ETOFFES OU D'ARTICLES NON-TISSES">
				FABRICATION D'ETOFFES OU D'ARTICLES NON-TISSES</option>
				
				<option style="width:300px;" value="252185" title="FABRICATION DE TULLES ET AUTRES TISSUS A MAILLE NOUEE">
				FABRICATION DE TULLES ET AUTRES TISSUS A MAILLE NOUEE</option>
				
				<option style="width:300px;" value="252186" title="FABRICATION DE VETEMENTS DE POUPEES">
				FABRICATION DE VETEMENTS DE POUPEES</option>
				
				<option style="width:300px;" value="252189" title="FABRICATION D'OBJETS DECORATIFS EN TISSU (PATCHWORKS, TISSUS APPLIQUES,...)">
				FABRICATION D'OBJETS DECORATIFS EN TISSU (PATCHWORKS, TISSUS APPLIQUES,...)</option>
				
				<option style="width:300px;" value="252190" title="FABRICATION D'OBJETS DIVERS EN TEXTILE (EN TOILE DE BATEAU, MADRAS, CROCHET, ETC)">
				FABRICATION D'OBJETS DIVERS EN TEXTILE (EN TOILE DE BATEAU, MADRAS, CROCHET, ETC)</option>
				
				<option style="width:300px;" value="252191" title="FABRICATION D'OUVRAGES DE PASSEMENTERIE">
				FABRICATION D'OUVRAGES DE PASSEMENTERIE</option>
				
				<option style="width:300px;" value="252192" title="FILATURE ET PREPARATION DE LA LAINE">
				FILATURE ET PREPARATION DE LA LAINE</option>
				
				<option style="width:300px;" value="252193" title="FILATURE PAR TOUTES TECHNIQUES DE TOUS TYPES DE FILS">
				FILATURE PAR TOUTES TECHNIQUES DE TOUS TYPES DE FILS</option>
				
				<option style="width:300px;" value="252194" title="PERSONNALISATION, MARQUAGE TEXTILE (VINYLE, SERIGRAPHIE, THERMOADHESIF, FLOCAGE, PEINTURE, RIVETS, ETC)">
				PERSONNALISATION, MARQUAGE TEXTILE (VINYLE, SERIGRAPHIE, THERMOADHESIF, FLOCAGE, PEINTURE, RIVETS, ETC)</option>
				
				<option style="width:300px;" value="252195" title="TISSAGE DE COTON">
				TISSAGE DE COTON</option>
				
				<option style="width:300px;" value="252196" title="TISSAGE DE LAINE">
				TISSAGE DE LAINE</option>
				
				<option style="width:300px;" value="252197" title="VOILERIE">
				VOILERIE</option>
				


/*AUTOMOBILE*/


				ACHAT REVENTE DE PIECES DETACHEES POUR L'AUTOMOBILE</option>
				
				<option style="width:300px;" value="252199" title="ACHAT REVENTE D'EQUIPEMENTS AUTOMOBILES">
				ACHAT REVENTE D'EQUIPEMENTS AUTOMOBILES</option>
				
				<option style="width:300px;" value="252200" title="AMENAGEMENT DE CAMPING CAR">
				AMENAGEMENT DE CAMPING CAR</option>
				
				<option style="width:300px;" value="252201" title="AMENAGEMENT DE VEHICULES">
				AMENAGEMENT DE VEHICULES</option>
				
				<option style="width:300px;" value="252202" title="CARROSSERIE, PEINTURE AUTOMOBILE">
				CARROSSERIE, PEINTURE AUTOMOBILE</option>
				
				<option style="width:300px;" value="252203" title="ENTREPRISE DE MECANIQUE MOTO, QUAD">
				ENTREPRISE DE MECANIQUE MOTO, QUAD</option>
				
				<option style="width:300px;" value="252204" title="ENTRETIEN REPARATION DE VEHICULES">
				ENTRETIEN REPARATION DE VEHICULES</option>
				
				<option style="width:300px;" value="252205" title="ENTRETIEN REPARATION DE VEHICULES SANS PERMIS">
				ENTRETIEN REPARATION DE VEHICULES SANS PERMIS</option>
				
				<option style="width:300px;" value="252206" title="EXPLOITATION D'UNE STATION DE LAVAGE AUTOMOBILE EN SELF SERVICE">
				EXPLOITATION D'UNE STATION DE LAVAGE AUTOMOBILE EN SELF SERVICE</option>
				
				<option style="width:300px;" value="252207" title="FABRICATION D'ACCESSOIRES AUTO, MOTO">
				FABRICATION D'ACCESSOIRES AUTO, MOTO</option>
				
				<option style="width:300px;" value="252208" title="FABRICATION D'ACCESSOIRES ELECTRONIQUES AUTOMOBILES">
				FABRICATION D'ACCESSOIRES ELECTRONIQUES AUTOMOBILES</option>
				
				<option style="width:300px;" value="252209" title="FABRICATION D'ACCESSOIRES POUR BICYCLETTES">
				FABRICATION D'ACCESSOIRES POUR BICYCLETTES</option>
				
				<option style="width:300px;" value="252210" title="FABRICATION D'ACCESSOIRES POUR MOTOCYCLES">
				FABRICATION D'ACCESSOIRES POUR MOTOCYCLES</option>
				
				<option style="width:300px;" value="252211" title="FABRICATION DE MODULES ELECTRIQUES POUR VOITURES DE COLLECTION">
				FABRICATION DE MODULES ELECTRIQUES POUR VOITURES DE COLLECTION</option>
				
				<option style="width:300px;" value="252212" title="FABRICATION DE MOTOCYCLES">
				FABRICATION DE MOTOCYCLES</option>
				
				<option style="width:300px;" value="252213" title="FABRICATION DE REMORQUES">
				FABRICATION DE REMORQUES</option>
				
				<option style="width:300px;" value="252214" title="LAVAGE DE VEHICULES CHEZ LES PARTICULIERS">
				LAVAGE DE VEHICULES CHEZ LES PARTICULIERS</option>
				
				<option style="width:300px;" value="252215" title="PEINTURE A L'AEROGRAPHE DE MOTOS, CASQUES">
				PEINTURE A L'AEROGRAPHE DE MOTOS, CASQUES</option>
				
				<option style="width:300px;" value="252216" title="PERSONNALISATION DE 2 ROUES">
				PERSONNALISATION DE 2 ROUES</option>
				
				<option style="width:300px;" value="252217" title="PERSONNALISATION DE VEHICULES (POSE DE FILM, ETC)">
				PERSONNALISATION DE VEHICULES (POSE DE FILM, ETC)</option>
				
				<option style="width:300px;" value="252218" title="PREPARATION DE MOTOS DE COMPETITION">
				PREPARATION DE MOTOS DE COMPETITION</option>
				
				<option style="width:300px;" value="252219" title="PREPARATION DE PEINTURES POUR CARROSSERIE AUTOMOBILE">
				PREPARATION DE PEINTURES POUR CARROSSERIE AUTOMOBILE</option>
				
				<option style="width:300px;" value="252220" title="REMORQUAGE DE VEHICULES">
				REMORQUAGE DE VEHICULES</option>
				
				<option style="width:300px;" value="252221" title="RENOVATION DE SCOOTER">
				RENOVATION DE SCOOTER</option>
				
				<option style="width:300px;" value="252222" title="REPARATION DE MOTOCYCLES">
				REPARATION DE MOTOCYCLES</option>
				
				<option style="width:300px;" value="252223" title="REPARATION DE MOTOCYCLES">
				REPARATION DE MOTOCYCLES</option>
				
				<option style="width:300px;" value="252224" title="REPARATION DE VEHICULES INDUSTRIELS">
				REPARATION DE VEHICULES INDUSTRIELS</option>
				
				<option style="width:300px;" value="252225" title="RESTAURATION DE VEHICULES ANCIENS">
				RESTAURATION DE VEHICULES ANCIENS</option>
				
				<option style="width:300px;" value="252226" title="TUNING">
				TUNING</option>
				
